### ISSUE TITLE
Fix support for importer() exporter() declaration

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#130]
Support writing a complete stream transformation in Fix language. E.g. in pseudo code:

myfixes.txt:

```
importer('LiveTemperatures', city => 'Ghent' , update => '+1 minute')

copy_field(temp.celcius,x.a)
copy_field(temp.date,x.b)
retain_field(x)

move_field(x.a,temperature)
move_field(x.b,date)
remove_field(x)

exporter('CSV')
```

shell:

```
$ catmandu < myfixes.txt 
```

or

```
#!/usr/bin/env catmandu
importer('LiveTemperatures', city => 'Ghent' , update => '+1 minute')

copy_field(temp.celcius,x.a)
copy_field(temp.date,x.b)
retain_field(x)

move_field(x.a,temperature)
move_field(x.b,date)
remove_field(x)

exporter('CSV')
```

**Comment by nichtich** [comment]
Could you please specify the expected behavior? For instance:

* `importer(...)` can only be the first statement of a fix script or it results in an error.
* `exporter(...)` can only be the last statement of a fix script  or it results in an error.
* `importer(...)` is silently ignored if importer is explicitly given:

        $ catmandu convert from JSON --fix myfixes.txt
        $ catmandu convert --fix myfixes.txt from JSON # equivalent or user will not understand

* `exporter(...)` is silently ignored if exporter is explicitly given:

        $ catmandu convert to JSON --fix myfixes.txt
        $ catmandu convert --fix myfixes.txt to JSON # equivalent or user will not understand

To execute a fix script:

    $ catmandu convert --fix myfixes.txt

In addition we could make the default action of catmandu to slurp a fix script from STDIN and do `convert` with this fix, so this would be equivalent:

    $ catmandu convert --fix myfixes.txt
    $ catmandu < myfixes.txt

**Comment by nichtich** [comment]
Implementing this feature would also close issue #91.

**Comment by phochste** [comment]
Available with the importer Bind

    #!/usr/bin/env catmandu run  
    do importer(OAI,url: "http://lib.ugent.be/oai") 
      retain(_id)
      add_to_exporter(.,YAML)
    end
