### ISSUE TITLE
Missing List::MoreUtils::XS dependency on 5.22.0

### ISSUE THREAD

**Issue by TineRobbe** [LibreCat/Catmandu#320]
**Problem**

I'm using perl 5.22.0 with plenv. I tried to install Catmandu with cpanm but I'm hitting an error. The installation fails when it tries to install List::MoreUtils.

The exact error from the log file mentions a missing List/MoreUtils/XS.pm file and it refers to a missing dependency List::MoreUtils::XS.

**Solution**

Manually installing List::MoreUtils::XS with cpanm and then trying to re-install catmandu works for me. 

Should the missing dependency on List::MoreUtils::XS be added to the catmandu cpanfile?

**Comment by netsensei** [comment]
This is related to [this issue](https://github.com/perl5-utils/List-MoreUtils/issues/25). Apparently, the XS bindings to List::MoreUtils were split off and made optional in case you don't need them i.e. when you install the module on a vendor that doesn't provide access to a compiler.

The problem is that detecting whether or not you need XS module is non-trivial if I understood correctly.  Moreover, the XS module is only required for running the test suite of List::MoreUtils.

This problem is environment related and pops up when using OSX + Plenv. Should be verified if this also happens on other platforms.

Other modules that depend on List::MoreUtils such as Dist::Milla fail to be installed to on OSX + Plenv without manually installing List::MoreUtils::XS.

**Comment by nics** [comment]
Version 1.0603 adds a hard dependency on the XS module. We were already dependent on a C compiler toolchain so it doesn't really matter.
