### ISSUE TITLE
Catmandu::CQLSearchable pod example sru_sortkeys is wrong?

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#376]
Shouldn't it be something like `title,,0` ? 

It would be helpfull to have these sru_sortkeys and a reference to Catmandu::CQLSearchable also in Catmandu::Searchable pod

**Comment by nics** [comment]
`title` is also valid I think, everything after the first argument gets replaced by the default if it's missing. But I changed the example since it illustrates sru syntax more clearly. I added a section about CQL to the Searchable pod.
Commits: 
684709909995dc2cd0046aaae54cdaac70d956f2
f68b96095186d72b4fd3dbc8e3fe5d48ba84305c
